// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsniULaOImpMOv2CUy-ILEWVQbegC0xqw',
    appId: '1:66513038922:web:cb8481024bc730e44d40b3',
    messagingSenderId: '66513038922',
    projectId: 'the-colour-app',
    authDomain: 'the-colour-app.firebaseapp.com',
    storageBucket: 'the-colour-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmlAh3ua6mozj_a7liAmYkWoryFlfgOO4',
    appId: '1:66513038922:android:c87e792b074bfd2f4d40b3',
    messagingSenderId: '66513038922',
    projectId: 'the-colour-app',
    storageBucket: 'the-colour-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0IVKH_Sv9nnXbjcPzIX20jwp48qb1qs8',
    appId: '1:66513038922:ios:e7ff2c419f7d73004d40b3',
    messagingSenderId: '66513038922',
    projectId: 'the-colour-app',
    storageBucket: 'the-colour-app.appspot.com',
    iosClientId:
        '66513038922-u3lrpquuasjjhgd8v9d4qjvbgjr1a6al.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
